name: Tests
on: [push, pull_request, workflow_dispatch]
jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.9.7
      - run: deno task check:publish
      - run: deno task tests
